### ISSUE TITLE
Добавить zigbee_ota.py

### ISSUE THREAD

**Issue by pvvx** [slacky1965/watermeter_zed#1]
Добавить [zigbee_ota.py](https://github.com/pvvx/ZigbeeTLc/blob/master/make/zigbee_ota.py)
Удалить [tl_check_fw2.exe](https://github.com/slacky1965/watermeter_zed/blob/main/tools/tl_check_fw2.exe) -> https://github.com/pvvx/ZigbeeTLc/blob/master/make/tl_check_fw.py

Учесть, что [TL_ZB_TIMER_SCHEDULE(app_reportXXXAttrTimerCb,...)](https://github.com/slacky1965/watermeter_zed/blob/main/src/app_reporting.c#L111C75-L111C75) назначает только один таймер с id равной адресу процедуры. А [в цикле](https://github.com/slacky1965/watermeter_zed/blob/main/src/app_reporting.c#L101) происходит переназначение... В итоге отрабатывает только один report, когда активность многих...

**Comment by slacky1965** [comment]
make_ota.py добавлен, просто не закоммичен. tl_check_fw2.exe не используется, просто лежит.

**Comment by pvvx** [comment]
По поводу пересечения версий для OTA для публикации.
Пока, известные мне номера:
https://github.com/pvvx/ZigbeeTLc/blob/master/src/common/comm_cfg.h#L71

**Comment by slacky1965** [comment]
Нужно поменять? Я в принципе не вижу проблемы. Но я ее могу не видеть ...

**Comment by pvvx** [comment]
Нет - не нужно, т.к. совпал с неиспользуемым BOARD_LYWSD03MMC_B17 и переименован в BOARD_WATERMETER
(используется только в BLE и не конфликтует)

**Comment by pvvx** [comment]
> Но я ее могу не видеть ...

Произойдет автоматическое обновление у всех пользователей z2m/zha/... после публикации в списки прошивок zigbee

**Comment by slacky1965** [comment]
А-а-а, понял. Но я не стремлюсь попасть в общую базу z2m, меня там нет. Так что вряд ли что-то обновится автоматически ...

**Comment by pvvx** [comment]
Если не озаботится с номерками, тогда ваш watermeter_zed обновится чем-то другим, если включите обновление :)

**Comment by slacky1965** [comment]
Но тогда получается бардак, нет согласования этих номеров. Я просто взял пример из SDK и посмотрел, как там. Там 0xFF зарезервирован за bootloader'ом и от 0x00 до 0x03 за примерами из SDK. Ну я взял просто следующий свободный 0x04. Также может поступить еще кто-то. Странно ...

**Comment by pvvx** [comment]
Я и пытаюсь согласовать со всеми, кто лепит под Telink ID.
Но там уже валяется прошивка "https://images.tuyaeu.com/smart/firmware/upgrade/20220907/1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin", которая постоянно закидывается в директорию для обновления ZHA...

**Comment by slacky1965** [comment]
Тогда может быть взять какой-то неиспользуемый ID, не от Телинка?

**Comment by pvvx** [comment]
Ни кто не сможет выложить в базу под вашим номером, если вы сами зарегистрируете там свою прошивку.

**Comment by pvvx** [comment]
Можно взять ваш конвертер для z2m для прикручивания к
https://pvvx.github.io/TS0201_TZ3000/
https://pvvx.github.io/DS01_zbeacon/
https://pvvx.github.io/TS0202_TZ3000/
и т.д.?
То есть тоже будут считать с двух выводов, плюс остальные функции типа: температуры/влажности/детектора движения и т.д. На всех таких устройствах, с модулем ZTU, есть выводы и обычно маркированы RX TX или есть позиции под разъем...

**Comment by slacky1965** [comment]
Все же в открытом доступе. Конечно можно :)

**Comment by pvvx** [comment]
П.платки то кто продает?
https://www.youtube.com/watch?v=cmuMv41pFuY
А у Tuya все уже готовое...
