### ISSUE TITLE
"оригинальный аглоритм reporting'а был заменен на кастомный"

### ISSUE THREAD

**Issue by pvvx** [slacky1965/watermeter_zed#21]
Этот алгоритм назначает таймеры. Число таймеров ограничено.
При вызове самой процедуры report, если в это время стек занят, SDK сам назначает таймер, чтобы использовать четверть секундную паузу между транзакциями (боится перегрузить роутеры и координатор) и запоминает данные в выделенной для этого памяти. Буферов в памяти хватает не десяток report, а вот таймеры ограничены.
В итоге, по описанному "кастомному" алгоритму может быть назначено несколько таймеров на один report и плодится ещё... и у вас включены все сервисы, которые тоже используют таймеры...

И просыпание по таймеру - это лишний расход батареи.
Постоянно отрабатывает timerPollRateEvt и можно привязаться к его пробуждению всей системы... Отключается во время потери координатора, во время поиска. Но тогда отрабатывают другие таймеры, но в этот период не вызываются  [poll процедуры](https://github.com/slacky1965/watermeter_zed/blob/main/src/watermeter.c#L255).

**Comment by slacky1965** [comment]
Таймеров по умолчанию 24. В Electricity Meter репортингов больше. Там это значение увеличено до 48 и все прекрасно работает.

**Comment by pvvx** [comment]
> Там это значение увеличено до 48 и все прекрасно работает.

c лишним расходом батареи.

**Comment by slacky1965** [comment]
> > Там это значение увеличено до 48 и все прекрасно работает.
> 
> c лишним расходом батареи.

А с оригинальным аглоритмом репортингов чип вообще не засыпает более, чем на 1 секунду ...

**Comment by pvvx** [comment]
По этому я использую другой алгоритм.

**Comment by slacky1965** [comment]
> По этому я использую другой алгоритм. С учетом того, что стек сам буферизирует выполнение report. Можно в цикле наплодить несколько report, а он потом их передает с необходимыми (если необходимы) паузами в четверть секунды. А у вас просто используется дублирование этой фичи.
> 
> В варианте одновременной работы BLE и Zigbee время на Zigbee стек отдается через промежутки передачи BLE рекламы. Выходит, что таймеры Zigbee накапливаются и исполняются пачкой дискретно этому шагу. В итоге общее потребление устройства выходит значительно меньше. Исключаются лишние пробуждения чипа по таймерам Zigbee. Создает это какие-то проблемы у других принимающих Zigbee – не знаю. Но это работает во всех конфигурациях что удалось проверить.

Хорошо, можно где-то поглядеть реализацию того, о чем Вы мне толкуете?

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc/blob/master/src/reporting.c
Но время для report-ов считается в другой процедуре, когда чип пробуждает кто другой.

**Comment by slacky1965** [comment]
> E

Спасибо, проверю. У меня в watermeter'е, с добавлением 2-х датчиков протечки, 5 endpoint'ов. Без проблем.

**Comment by pvvx** [comment]
Не выходит - ZHA не жрет.
Так же не жрет 2..3 батарейки. Только одну.
