### ISSUE TITLE
Ошибка в логе home assistant "Invalid value for number.watermeter_hot_water_preset ...  (range 0.0 - 100.0)"

### ISSUE THREAD

**Issue by smi71** [slacky1965/watermeter_zed#28]
Logger: homeassistant.components.mqtt.number
Source: components/mqtt/number.py:182
integration: MQTT (documentation, issues)
First occurred: 10:43:47 (4 occurrences)
Last logged: 10:44:28

Invalid value for number.watermeter_hot_water_preset: 1596140 (range 0.0 - 100.0)
Invalid value for number.watermeter_cold_water_preset: 1779900 (range 0.0 - 100.0)

Home Assistant
Core
2024.6.0
Supervisor
2024.06.0
Operating System
12.3
Frontend
20240605.0

Zigbee2MQTT
Current version: 1.38.0-1

**Comment by Chepaeff** [comment]
Same error:

ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.watermeter_cold_water_preset: 20263 (range 0.0 - 100.0)

Home Assistant
Core
2024.10.3
Supervisor
2024.10.2
Zigbee2MQTT
Current version: 1.40.2-1

**Comment by slacky1965** [comment]
https://github.com/slacky1965/watermeter_zed?tab=readme-ov-file#home-assistant

**Comment by slacky1965** [comment]
Заморочился я этими ошибками. В общем не понятно кто виноват. Но факт, что в HA это выглядит криво - наложилось какое-то ограничение на предустановки счетчиков от 0 до 100.

В общем, скачайте новый конвертор и все нормализуется.

![HA_device](https://github.com/user-attachments/assets/de7af9a0-c74b-4e9b-aaa2-7e06db87fc27)
